# Generated by Django 2.0.9 on 2019-01-17 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esp_instrument', '0002_deployment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspDatapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(blank=True, max_length=20)),
                ('measurement_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('algal_species', models.CharField(blank=True, choices=[('Alexandrium fundyense', 'Alexandrium fundyense'), ('Pseudonitzschia', 'Pseudonitzschia')], max_length=50)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esp_datapoint', to='esp_instrument.Deployment')),
            ],
            options={
                'ordering': ['-measurement_date'],
            },
        ),
    ]
