# Generated by Django 2.2.4 on 2019-08-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0004_auto_20190823_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='closurearea',
            name='current_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='closurearea',
            name='area_class',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='closurearea',
            name='area_description',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
    ]
