# Generated by Django 2.2.4 on 2019-08-26 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0007_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='ClosureNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notice_action', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=50)),
                ('syndrome', models.CharField(blank=True, choices=[('PSP', 'Paralytic Shellfish Poison (PSP)'), ('DSP', 'Diarrhetic shellfish poisoning (DSP)'), ('ASP', 'Amnesic shellfish poisoning (ASP)')], default='PSP', max_length=50)),
                ('closure_areas', models.ManyToManyField(to='closures.ClosureArea')),
                ('species', models.ManyToManyField(to='closures.Species')),
            ],
            options={
                'ordering': ['date', 'title'],
            },
        ),
    ]
