# Generated by Django 2.2.4 on 2019-08-30 17:32

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0010_auto_20190827_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurearea',
            name='geom',
            field=djgeojson.fields.MultiPolygonField(),
        ),
    ]
