# Generated by Django 2.2.4 on 2019-09-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0012_auto_20190906_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurenotice',
            name='closure_areas',
            field=models.ManyToManyField(related_name='closure_notices', to='closures.ClosureArea'),
        ),
        migrations.AlterField(
            model_name='closurenotice',
            name='species',
            field=models.ManyToManyField(related_name='closure_notices', to='closures.Species'),
        ),
    ]
