# Generated by Django 2.2.4 on 2019-09-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0013_auto_20190906_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='closurenotice',
            name='causative_organism',
            field=models.CharField(blank=True, choices=[('Alexandrium spp.', 'Alexandrium spp.'), ('Dinophysis sp.', 'Dinophysis sp.')], max_length=50),
        ),
        migrations.AddField(
            model_name='closurenotice',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='closurenotice',
            name='document',
            field=models.FileField(null=True, upload_to='closure_notices/'),
        ),
    ]
