# Generated by Django 2.2.4 on 2019-09-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0017_causativeorganism'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closurenotice',
            old_name='causative_organism',
            new_name='organism',
        ),
    ]
