# Generated by Django 2.2.4 on 2019-09-16 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0018_auto_20190916_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='closurenotice',
            name='causative_organism',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closure_notices', to='closures.CausativeOrganism'),
        ),
    ]
