# Generated by Django 2.2.4 on 2019-09-16 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0019_closurenotice_causative_organism'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurenotice',
            name='causative_organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closure_notices', to='closures.CausativeOrganism'),
        ),
    ]
