# Generated by Django 2.2.4 on 2019-09-24 13:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0021_remove_closurenotice_organism'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShellfishArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, choices=[('ME', 'Maine'), ('MA', 'Massachusetts'), ('NH', 'New Hampshire')], db_index=True, max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('acres', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('area_description', models.CharField(blank=True, max_length=1000)),
                ('area_class', models.CharField(blank=True, max_length=100)),
                ('current_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=100)),
            ],
            options={
                'ordering': ['state', 'name'],
            },
        ),
    ]
