# Generated by Django 2.2.4 on 2019-09-30 19:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0026_exceptionarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAreaShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('state', models.CharField(blank=True, choices=[('ME', 'Maine'), ('MA', 'Massachusetts'), ('NH', 'New Hampshire')], db_index=True, max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
