# Generated by Django 2.2.4 on 2019-10-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0028_closurenotice_custom_borders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closurenotice',
            name='east_border',
        ),
        migrations.RemoveField(
            model_name='closurenotice',
            name='west_border',
        ),
    ]
