# Generated by Django 2.2.4 on 2019-10-01 14:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0029_auto_20191001_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='closurenotice',
            name='custom_geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
