# Generated by Django 2.2.6 on 2019-11-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0034_remove_exceptionarea_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='closurenotice',
            name='border_east',
            field=models.ManyToManyField(related_name='closure_notices_east', to='closures.Landmark'),
        ),
        migrations.AddField(
            model_name='closurenotice',
            name='border_west',
            field=models.ManyToManyField(related_name='closure_notices_west', to='closures.Landmark'),
        ),
    ]
