# Generated by Django 2.2.8 on 2020-02-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0042_closuredataevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closuredataevent',
            name='end_date',
        ),
    ]
