# Generated by Django 2.2.8 on 2020-02-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0043_remove_closuredataevent_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closuredataevent',
            old_name='start_date',
            new_name='effective_date',
        ),
    ]
