# Generated by Django 2.2.8 on 2020-02-21 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0044_auto_20200205_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closurenotice',
            options={'ordering': ['effective_date', 'title']},
        ),
        migrations.RenameField(
            model_name='closurenotice',
            old_name='notice_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='closuredataevent',
            name='causative_organism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closure_data_events', to='closures.CausativeOrganism'),
        ),
        migrations.AlterField(
            model_name='closuredataevent',
            name='closure_notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_data_events', to='closures.ClosureNotice'),
        ),
        migrations.AlterField(
            model_name='closuredataevent',
            name='shellfish_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_data_events', to='closures.ShellfishArea'),
        ),
        migrations.AlterField(
            model_name='closuredataevent',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_data_events', to='closures.Species'),
        ),
    ]
