# Generated by Django 2.2.8 on 2020-02-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0045_auto_20200221_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closurenotice',
            options={'get_latest_by': 'effective_date', 'ordering': ['effective_date', 'title']},
        ),
    ]
