# Generated by Django 2.2.8 on 2020-03-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0046_auto_20200227_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellfisharea',
            name='atlas_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
