# Generated by Django 2.2.8 on 2020-03-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0047_shellfisharea_atlas_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellfisharea',
            name='is_atlas_combined_area',
            field=models.BooleanField(default=False),
        ),
    ]
