# Generated by Django 2.2.8 on 2020-06-25 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0049_shellfishareaimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='closuredataevent',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
