# Generated by Django 2.2.13 on 2020-07-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0051_auto_20200630_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurenotice',
            name='border_east',
            field=models.ManyToManyField(blank=True, related_name='closure_notices_east', to='closures.Landmark'),
        ),
        migrations.AlterField(
            model_name='closurenotice',
            name='border_west',
            field=models.ManyToManyField(blank=True, related_name='closure_notices_west', to='closures.Landmark'),
        ),
    ]
