version: '3.7'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_nginx: {}
  static_volume_habhub: {}
  media_volume_habhub: {}

services:
  react_frontend:
    image: eandrewswhoi/hab-hub-frontend-client:latest
    environment:
      - "REACT_APP_API_URL=https://habhub.whoi.edu/services/"

  django: &django
    image: eandrewswhoi/hab-hub-django-dataserver:latest
    #container_name: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static_volume_habhub:/app/staticfiles  # <-- bind the static files
      - media_volume_habhub:/app/media  # <-- bind the media files
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    restart: unless-stopped
    command: /start

  postgres:
    image: eandrewswhoi/postgres-postgis-django:12
    container_name: postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped

  nginx:
    image: nginx:1.15
    container_name: nginx
    depends_on:
      - django
      - react_frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - production_nginx:/var/log/nginx
      - ./.ssl/whoi_certs:/etc/ssl/whoi_certs:ro # bind a local directory with the WHOI SSL certs
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped

  redis:
    image: redis:6.0

  celeryworker:
    <<: *django
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    depends_on:
      - redis
      - postgres

    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    ports:
      - "5555:5555"
    command: /start-flower
