version: "3.7"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  react_frontend:
    build:
      context: .
      dockerfile: ./compose/local/react-frontend/Dockerfile
    image: habhub_local_react_frontend
    volumes:
      - ./habhub-react-frontend:/usr/src/app
      - /usr/src/app/node_modules #<- Use anonymous volume to keep node_modules directory
    ports:
      - "3000:3000"
    networks:
      - ifcbdb_nginx_network
    command: npm start

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: habhub_local_django
    depends_on:
      - postgres_habhub
    volumes:
      - ./habhub-dataserver:/app
    env_file:
      - ./habhub-dataserver/.envs/.local/.django
      - ./habhub-dataserver/.envs/.local/.postgres
    ports:
      - "8888:8000"
    networks:
      - ifcbdb_nginx_network
    command: /start

  postgres_habhub:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: habhub_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    networks:
      - ifcbdb_nginx_network
    env_file:
      - ./habhub-dataserver/.envs/.local/.postgres

  celeryworker:
    <<: *django
    image: habhub_local_celeryworker
    depends_on:
      - redis
      - postgres_habhub
    ports: []
    networks:
      - ifcbdb_nginx_network
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: habhub_local_celerybeat
    depends_on:
      - redis
      - postgres_habhub
    ports: []
    networks:
      - ifcbdb_nginx_network
    command: /start-celerybeat

  redis_habhub:
    image: redis:6.0
    restart: unless-stopped
    networks:
      - ifcbdb_nginx_network

networks:
  default:
    external:
      name: ifcbdb_nginx_network
