# Generated by Django 2.2.8 on 2019-12-19 18:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('system_type', models.CharField(blank=True, choices=[('Monitoring', 'Monitoring'), ('Forecasting', 'Forecasting')], default='Monitoring', max_length=50)),
                ('url', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('alt_url', models.URLField()),
                ('alt_location', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
