# Generated by Django 2.2.8 on 2020-01-06 17:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_systems', '0003_auto_20200106_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringsystem',
            name='system_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monitoring', 'Monitoring'), ('Forecasting', 'Forecasting')], default='Monitoring', max_length=100),
        ),
    ]
