# Generated by Django 2.2.8 on 2020-03-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_auto_20200302_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
    ]
