# Generated by Django 2.2.8 on 2020-03-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_auto_20200303_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='measurement',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
