# Generated by Django 2.2.8 on 2020-03-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_datapoint_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='measurement',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
