# Generated by Django 2.2.8 on 2020-03-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_remove_datapoint_measurement_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'get_latest_by': 'measurement_date', 'ordering': ['-measurement_date']},
        ),
    ]
