# Generated by Django 3.0.10 on 2020-12-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0019_auto_20201229_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
