# Generated by Django 2.0.9 on 2019-03-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifcb_cruises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifcbdatapoint',
            name='file_name',
            field=models.CharField(max_length=100),
        ),
    ]
