# Generated by Django 2.0.9 on 2019-01-07 20:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp_instrument', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('mooring_name', models.CharField(max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2019)])),
                ('espinstrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment', to='esp_instrument.EspInstrument')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
    ]
