# Generated by Django 2.2.4 on 2019-08-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurearea',
            name='acres',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='closurearea',
            name='area_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='closurearea',
            name='area_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
