# Generated by Django 2.2.4 on 2019-08-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0002_auto_20190823_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurearea',
            name='area_class',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='closurearea',
            name='area_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
