# Generated by Django 2.2.4 on 2019-08-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0003_auto_20190823_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closurearea',
            old_name='geometry',
            new_name='geom',
        ),
    ]
