# Generated by Django 2.2.4 on 2019-08-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0005_auto_20190826_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurearea',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Warning', 'Warning')], default='Open', max_length=100),
        ),
    ]
