# Generated by Django 2.2.4 on 2019-08-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0008_auto_20190826_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterField(
            model_name='closurearea',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=100),
        ),
        migrations.AlterField(
            model_name='closurearea',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='closurearea',
            name='state',
            field=models.CharField(blank=True, choices=[('ME', 'Maine'), ('MA', 'Massachusetts'), ('NH', 'New Hampshire')], db_index=True, max_length=50),
        ),
    ]
