# Generated by Django 2.2.4 on 2019-09-06 13:27

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0011_auto_20190830_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closurearea',
            name='geom',
            field=djgeojson.fields.PolygonField(),
        ),
    ]
