# Generated by Django 2.2.4 on 2019-09-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0022_shellfisharea'),
    ]

    operations = [
        migrations.AddField(
            model_name='closurenotice',
            name='shellfish_areas',
            field=models.ManyToManyField(related_name='closure_notices', to='closures.ShellfishArea'),
        ),
    ]
