# Generated by Django 2.2.4 on 2019-09-27 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0023_closurenotice_shellfish_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureNoticeMaine',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('closures.closurenotice',),
        ),
        migrations.AlterModelOptions(
            name='closurenotice',
            options={'ordering': ['notice_date', 'title']},
        ),
        migrations.RenameField(
            model_name='closurenotice',
            old_name='date',
            new_name='notice_date',
        ),
        migrations.AddField(
            model_name='closurenotice',
            name='effective_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
