# Generated by Django 2.2.4 on 2019-09-27 14:23

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0024_auto_20190927_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closurenoticemaine',
            options={'verbose_name': 'Closure notice (Maine)', 'verbose_name_plural': 'Closure notices (Maine)'},
        ),
        migrations.AddField(
            model_name='closurenotice',
            name='east_border',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='closurenotice',
            name='west_border',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
