# Generated by Django 2.2.4 on 2019-10-01 13:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0027_baseareashape'),
    ]

    operations = [
        migrations.AddField(
            model_name='closurenotice',
            name='custom_borders',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
    ]
