# Generated by Django 2.2.4 on 2019-10-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0030_closurenotice_custom_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closurenotice',
            name='closure_areas',
        ),
        migrations.DeleteModel(
            name='ClosureArea',
        ),
    ]
