# Generated by Django 2.2.6 on 2019-11-18 16:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0031_auto_20191003_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('state', models.CharField(blank=True, choices=[('ME', 'Maine'), ('MA', 'Massachusetts'), ('NH', 'New Hampshire')], default='ME', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
