# Generated by Django 2.2.6 on 2019-11-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0036_auto_20191127_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='closurenotice',
            name='data_source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
