# Generated by Django 2.2.8 on 2020-02-03 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0038_landmark_shellfish_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shellfisharea',
            name='current_status',
        ),
    ]
