# Generated by Django 2.2.8 on 2020-02-03 20:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0039_remove_shellfisharea_current_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shellfisharea',
            managers=[
                ('current_status', django.db.models.manager.Manager()),
            ],
        ),
    ]
