# Generated by Django 2.2.8 on 2020-02-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0040_auto_20200203_1555'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='shellfisharea',
            managers=[
            ],
        ),
    ]
