# Generated by Django 2.2.8 on 2020-02-04 20:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0041_auto_20200203_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosureDataEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notice_action', models.CharField(default='Open', max_length=50)),
                ('causative_organism', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='closure_data_points', to='closures.CausativeOrganism')),
                ('closure_notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_data_points', to='closures.ClosureNotice')),
                ('shellfish_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_data_points', to='closures.ShellfishArea')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_data_points', to='closures.Species')),
            ],
        ),
    ]
