# Generated by Django 2.2.8 on 2020-03-06 18:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0048_shellfisharea_is_atlas_combined_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShellfishAreaImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, choices=[('ME', 'Maine'), ('MA', 'Massachusetts'), ('NH', 'New Hampshire')], db_index=True, max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('acres', models.DecimalField(decimal_places=10, max_digits=19, null=True)),
                ('area_description', models.CharField(blank=True, max_length=1000)),
                ('area_class', models.CharField(blank=True, max_length=100)),
                ('atlas_key', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['state', 'name'],
            },
        ),
    ]
