# Generated by Django 2.2.8 on 2020-06-30 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0050_closuredataevent_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='closuredataevent',
            options={'get_latest_by': 'effective_date'},
        ),
        migrations.AlterModelOptions(
            name='closurenotice',
            options={'get_latest_by': 'effective_date', 'ordering': ['-effective_date', 'title']},
        ),
    ]
