# Generated by Django 3.0.10 on 2021-01-19 14:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0052_auto_20200718_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='shellfisharea',
            name='geom_center_point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
