# Generated by Django 4.2.14 on 2026-08-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closures', '0054_auto_20231128_1935'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='closurenotice',
            index=models.Index(fields=['notice_action', 'effective_date'], name='closurenotice_action_date_idx'),
        ),
    ]
