export const species = [
  {
    'id': 'Alexandrium_catenella',
    'speciesName': 'Alexandrium catenella',
    'syndrome': 'PSP',
    'visibility': true,
    'colorPrimary': '#de2d26',
    'colorGradient': ['#fee5d9', '#fcae91', '#fb6a4a', '#de2d26', '#a50f15'],
  },
  {
    'id': 'Dinophysis_acuminata',
    'speciesName': 'Dinophysis acuminata',
    'syndrome': 'DSP',
    'visibility': true,
    'colorPrimary': '#3182bd',
    'colorGradient': ['#eff3ff', '#bdd7e7', '#6baed6', '#3182bd', '#08519c'],
  },
  {
    'id': 'Dinophysis_norvegica',
    'speciesName': 'Dinophysis norvegica',
    'syndrome': 'DSP',
    'visibility': true,
    'colorPrimary': '#756bb1',
    'colorGradient': ['#f2f0f7', '#cbc9e2', '#9e9ac8', '#756bb1', '#54278f'],
  },
  {
    'id': 'Karenia',
    'speciesName': 'Karenia',
    'syndrome': 'Fish Killing',
    'visibility': true,
    'colorPrimary': '#636363',
    'colorGradient': ['#f7f7f7', '#cccccc', '#969696', '#636363', '#252525'],
  },
  {
    'id': 'Margalefidinium',
    'speciesName': 'Margalefidinium polykrikoides',
    'syndrome': 'Fish Killing',
    'visibility': true,
    'colorPrimary': '#e6550d',
    'colorGradient': ['#feedde', '#fdbe85', '#fd8d3c', '#e6550d', '#a63603'],
  },
  {
    'id': 'Pseudo-nitzschia',
    'speciesName': 'Pseudo nitzschia',
    'syndrome': 'ASP',
    'visibility': true,
    'colorPrimary': '#31a354',
    'colorGradient': ['#edf8e9', '#bae4b3', '#74c476', '#31a354', '#006d2c'],
  },
];
