# Generated by Django 2.0.9 on 2018-12-18 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_datapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoint', to='stations.Station'),
        ),
    ]
