# Generated by Django 2.2.8 on 2020-03-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0014_auto_20200303_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoint',
            name='measurement_old',
        ),
    ]
