# Generated by Django 3.0.10 on 2020-11-26 19:25

import django.contrib.postgres.fields
from django.db import migrations, models
import habhub.stations.models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0016_auto_20200306_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='hab_species',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Alexandrium_catenella', 'Alexandrium catenella'), ('Dinophysis_acuminata', 'Dinophysis acuminata'), ('Dinophysis_norvegica', 'Dinophysis norvegica'), ('Karenia', 'Karenia'), ('Margalefidinium', 'Margalefidinium polykrikoides'), ('Pseudo-nitzschia', 'Pseudo nitzschia')], max_length=50), default=habhub.stations.models.get_hab_species_default, size=None),
        ),
    ]
