# Generated by Django 3.0.10 on 2020-11-26 19:53

from django.db import migrations, models
import habhub.core.fields
import habhub.stations.models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_station_hab_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='hab_species',
            field=habhub.core.fields.ChoiceArrayField(base_field=models.CharField(choices=[('Alexandrium_catenella', 'Alexandrium catenella'), ('Dinophysis_acuminata', 'Dinophysis acuminata'), ('Dinophysis_norvegica', 'Dinophysis norvegica'), ('Karenia', 'Karenia'), ('Margalefidinium', 'Margalefidinium polykrikoides'), ('Pseudo-nitzschia', 'Pseudo nitzschia')], max_length=50), default=habhub.stations.models.get_hab_species_default, size=None),
        ),
    ]
