# Generated by Django 2.2.8 on 2020-01-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_systems', '0002_auto_20200106_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringsystem',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
