# Generated by Django 2.2.8 on 2020-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_systems', '0004_auto_20200106_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringsystem',
            name='latitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='monitoringsystem',
            name='longitude',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
