# Generated by Django 2.0.9 on 2019-03-21 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruise_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IFCBDatapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=18, max_digits=20)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ifcb_datapoint', to='ifcb_cruises.Cruise')),
            ],
            options={
                'ordering': ['file_name'],
            },
        ),
    ]
