# Generated by Django 3.0.10 on 2021-04-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=100)),
            ],
            options={
                'ordering': ['species_id'],
            },
        ),
    ]
