# Generated by Django 3.0.10 on 2021-04-12 17:31

import colorfield.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TargetSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.CharField(db_index=True, help_text='Needs to match the species ID used in the Autoclass files from the IFCB Dashboard', max_length=100, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=100)),
                ('syndrome', models.CharField(blank=True, max_length=100)),
                ('primary_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('color_gradient', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), blank=True, default=None, null=True, size=None)),
            ],
            options={
                'verbose_name_plural': 'Target Species',
                'ordering': ['species_id'],
            },
        ),
    ]
