# Generated by Django 3.0.10 on 2021-04-05 15:10

from django.db import migrations

def create_target_species(apps, schema_editor):
    # create initial HAB species to populate TargetSpecies
    # species_id needs to match the Autoclass files in the IFCB Dashboard
    TargetSpecies = apps.get_model('core', 'TargetSpecies')

    # default Species
    ALEXANDRIUM_CATENELLA = 'Alexandrium_catenella'
    DINOPHYSIS_ACUMINATA = 'Dinophysis_acuminata'
    DINOPHYSIS_NORVEGICA = 'Dinophysis_norvegica'
    KARENIA = 'Karenia'
    MARGALEFIDINIUM = 'Margalefidinium'
    PSEUDO_NITZSCHIA = 'Pseudo-nitzschia'
    TARGET_SPECIES = (
        (ALEXANDRIUM_CATENELLA, 'Alexandrium catenella'),
        (DINOPHYSIS_ACUMINATA, 'Dinophysis acuminata'),
        (DINOPHYSIS_NORVEGICA, 'Dinophysis norvegica'),
        (KARENIA, 'Karenia'),
        (MARGALEFIDINIUM, 'Margalefidinium polykrikoides'),
        (PSEUDO_NITZSCHIA, 'Pseudo nitzschia'),
    )

    for species in TARGET_SPECIES:
        species, created = TargetSpecies.objects.get_or_create(
            species_id=species[0],
            display_name=species[1]
        )

def create_data_layers(apps, schema_editor):
    # create initial Data Layers that are available
    DataLayer = apps.get_model('core', 'DataLayer')

    # default Data Layers
    DATA_LAYERS = (
        ('ifcb-layer', 'IFCB Cell Concentration'),
        ('stations-layer', 'Shellfish Toxicity'),
        ('closures-layer', 'Shellfish Bed Closures'),
    )

    for layer in DATA_LAYERS:
        layer, created = DataLayer.objects.get_or_create(
            layer_id=layer[0],
            name=layer[1],
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_target_species),
        migrations.RunPython(create_data_layers),
    ]
