# Generated by Django 3.0.10 on 2021-04-05 15:10

from django.db import migrations

def create_target_species(apps, schema_editor):
    # create initial HAB species to populate TargetSpecies
    # species_id needs to match the Autoclass files in the IFCB Dashboard
    TargetSpecies = apps.get_model('core', 'TargetSpecies')

    # default Species
    TARGET_SPECIES_INITIAL = [
        {
        'id': "Alexandrium_catenella",
        'display_name': "Alexandrium catenella",
        'syndrome': "PSP",
        'primary_color': "#e31a1c",
        'colorGradient': ["#fee5d9", "#fcae91", "#fb6a4a", "#e31a1c", "#a50f15"]
        },
        {
        'id': "Dinophysis_acuminata",
        'display_name': "Dinophysis acuminata",
        'syndrome': "DSP",
        'primary_color': "#1f78b4",
        'colorGradient': ["#eff3ff", "#bdd7e7", "#6baed6", "#1f78b4", "#08519c"]
        },
        {
        'id': "Dinophysis_norvegica",
        'display_name': "Dinophysis norvegica",
        'syndrome': "DSP",
        'primary_color': "#9e9e9e",
        'colorGradient': ["#fafafa", "#eeeeee", "#bdbdbd", "#9e9e9e", "#616161"]
        },
        {
        'id': "Karenia",
        'display_name': "Karenia",
        'syndrome': "Fish Kills",
        'primary_color': "#33a02c",
        'colorGradient': ["#edf8e9", "#bae4b3", "#74c476", "#33a02c", "#006d2c"]
        },
        {
        'id': "Margalefidinium",
        'display_name': "Margalefidinium polykrikoides",
        'syndrome': "Fish Kills",
        'primary_color': "#ffeb3b",
        'colorGradient': ["#fffde7", "#fff59d", "#fff176", "#ffeb3b", "#fdd835"]
        },
        {
        'id': "Pseudo-nitzschia",
        'display_name': "Pseudo-nitzschia",
        'syndrome': "ASP",
        'primary_color': "#673ab7",
        'colorGradient': ["#ede7f6", "#d1c4e9", "#9575cd", "#673ab7", "#311b92"]
        }
    ]

    for species in TARGET_SPECIES_INITIAL:
        print(species)
        species_obj, created = TargetSpecies.objects.get_or_create(
            species_id=species['id'],
            defaults={
                'display_name': species['display_name'],
                'syndrome': species['syndrome'],
                'primary_color': species['primary_color']
            },
        )

def create_data_layers(apps, schema_editor):
    # create initial Data Layers that are available
    DataLayer = apps.get_model('core', 'DataLayer')

    # default Data Layers
    DATA_LAYERS = (
        ('ifcb-layer', 'IFCB Cell Concentration'),
        ('stations-layer', 'Shellfish Toxicity'),
        ('closures-layer', 'Shellfish Bed Closures'),
    )

    for layer in DATA_LAYERS:
        layer_obj, created = DataLayer.objects.get_or_create(
            layer_id=layer[0],
            name=layer[1],
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_target_species),
        migrations.RunPython(create_data_layers),
    ]
