# Generated by Django 3.0.10 on 2021-08-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210412_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetspecies',
            name='species_environment',
            field=models.CharField(choices=[('Saltwater', 'Saltwater'), ('Freshwater', 'Freshwater')], default='Saltwater', max_length=20),
        ),
    ]
