# Generated by Django 3.0.10 on 2021-04-05 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210405_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetspecies',
            options={'ordering': ['species_id'], 'verbose_name_plural': 'Target Species'},
        ),
    ]
