# Generated by Django 3.0.10 on 2021-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_targetspecies_species_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetspecies',
            name='species_environment',
            field=models.CharField(choices=[('MARINE', 'MARINE'), ('Freshwater', 'Freshwater')], default='MARINE', max_length=20),
        ),
    ]
