# Generated by Django 3.0.10 on 2021-04-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210405_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetspecies',
            name='species_id',
            field=models.CharField(db_index=True, help_text='Needs to match the species ID used in the Autoclass files from the IFCB Dashboard', max_length=100, unique=True),
        ),
    ]
