# Generated by Django 3.0.10 on 2021-04-05 20:55

import colorfield.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210405_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetspecies',
            name='color_gradient',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='targetspecies',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AddField(
            model_name='targetspecies',
            name='syndrome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
