# Generated by Django 3.0.10 on 2021-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210819_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetspecies',
            name='species_environment',
            field=models.CharField(choices=[('Marine', 'Marine'), ('Freshwater', 'Freshwater')], default='Marine', max_length=20),
        ),
    ]
