# Generated by Django 3.0.10 on 2021-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210405_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetspecies',
            name='display_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
