# Generated by Django 3.0.10 on 2021-08-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_metric"),
    ]

    operations = []
