# Generated by Django 3.0.10 on 2021-08-29 13:33

from django.db import migrations
from ..constants import DATA_LAYERS, METRICS

def create_metrics(apps, schema_editor):
    # create initial Metrics for IFCB Data Layer that are available
    Metric = apps.get_model('core', 'Metric')
    DataLayer = apps.get_model('core', 'DataLayer')

    for metric in METRICS:
        try:
            data_layer = DataLayer.objects.get(layer_id=metric[3])
            print(data_layer)
        except DataLayer.DoesNotExist:
            continue

        metric_obj, created = Metric.objects.get_or_create(
            metric_id=metric[0],
            name=metric[1],
            units=metric[2],
            data_layer=data_layer
        )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_metric'),
    ]

    operations = [
        migrations.RunPython(create_metrics),
    ]
