# Generated by Django 3.0.10 on 2021-08-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210829_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='belongs_to_app',
            field=models.CharField(choices=[('ifcb_datasets', 'Ifcb_Datasets'), ('stations', 'Stations'), ('closures', 'Closures')], db_index=True, default='ifcb_datasets', max_length=100),
        ),
    ]
