# Generated by Django 3.0.10 on 2021-11-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_datalayer_belongs_to_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='data_layers',
            field=models.ManyToManyField(related_name='metrics', to='core.DataLayer'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='data_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='core.DataLayer'),
        ),
    ]
