# Generated by Django 3.0.10 on 2021-11-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211105_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='data_layer',
        ),
    ]
