# Generated by Django 3.0.10 on 2022-01-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20211105_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetspecies',
            name='autoclass_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
