# Generated by Django 3.0.10 on 2022-01-04 16:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_targetspecies_autoclass_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetspecies',
            name='autoclass_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
