# Generated by Django 3.1.14 on 2023-02-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mapbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetspecies',
            name='species_type',
            field=models.CharField(choices=[('HAB', 'HAB'), ('Other', 'Other')], default='HAB', max_length=20),
        ),
    ]
