# Generated by Django 3.1.14 on 2023-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_targetspecies_species_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapbookmark',
            name='max_mean',
            field=models.CharField(default='mean', max_length=20),
        ),
    ]
