# Generated by Django 3.1.14 on 2023-03-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_mapbookmark_active_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapbookmark',
            name='relative_date_range',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
