# Generated by Django 3.1.14 on 2023-06-14 10:32

from django.db import migrations
from ..constants import DATA_LAYERS, METRICS


def create_data_layers(apps, schema_editor):
    # reset and create new Data Layers that match expected data
    DataLayer = apps.get_model("core", "DataLayer")
    Metric = apps.get_model("core", "Metric")

    # remove any existing layers
    layers = DataLayer.objects.all()
    layers.delete()

    # create new layers
    for layer in DATA_LAYERS:
        layer_obj = DataLayer.objects.create(
            layer_id=layer[0], name=layer[1], is_active=True
        )

    # add metrics to layers
    for metric in METRICS:
        metric_obj = Metric.objects.get(metric_id=metric[0])
        for layer_id in metric[3]:
            try:
                layer = DataLayer.objects.get(layer_id=layer_id)
                metric_obj.data_layers.add(layer)
            except Exception as e:
                print(e)
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_mapbookmark_relative_date_range"),
    ]

    operations = [
        migrations.RunPython(create_data_layers),
    ]
