# Generated by Django 4.2.14 on 2026-08-09 18:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20231128_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetspecies',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
