# Generated by Django 2.0.9 on 2018-12-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='state',
            field=models.CharField(blank=True, choices=[('Maine', 'Maine'), ('Massachusetts', 'Massachusetts')], max_length=50),
        ),
    ]
