# Generated by Django 2.0.9 on 2018-12-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_auto_20181217_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ['state', 'station_name']},
        ),
    ]
