# Generated by Django 2.0.9 on 2019-01-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_datapoint_species'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['-measurement_date']},
        ),
    ]
