version: "3"

services:
  node_filewatcher_app:
    build:
      context: .
    image: node_fileuploader_aws
    volumes:
      - /opt/ifcbdb/ifcbdb/ifcb_data/primary/:/usr/src/app/data_files

    env_file:
      - ./.env
    restart: "no"
    #command: node app.js
