# Generated by Django 2.0.9 on 2019-01-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_instrument', '0003_espdatapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espdatapoint',
            name='algal_species',
            field=models.CharField(blank=True, choices=[('Alexandrium fundyense', 'Alexandrium fundyense'), ('Pseudonitzschia', 'Pseudonitzschia')], default='Alexandrium fundyense', max_length=50),
        ),
    ]
