# Generated by Django 3.0.10 on 2021-01-01 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_instrument', '0005_auto_20200106_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
