# Generated by Django 3.0.10 on 2022-01-04 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_instrument', '0006_auto_20210101_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
