# Generated by Django 3.1.14 on 2023-02-06 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_instrument', '0007_auto_20220104_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
