# Generated by Django 3.2.23 on 2023-11-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_instrument', '0008_auto_20230206_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='espdatapoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='espinstrument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
