# Generated by Django 4.2.14 on 2026-08-09 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_instrument', '0009_auto_20231128_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
